"""Deterministic repo philosophy cards.

A card is a short, citable description of one repository's conventions, built
by scanning that repository's *committed* config. Cards exist to be passed to
:func:`harness.brief.build_brief` as ordinary citable windows, which puts them
inside ``brief.py``'s ``GROUNDING_RULES``: a consumer may only cite what the
pack quotes, and an uncited assertion is invalid.

That is the whole design constraint, and it drives the schema. A card row that
asserts a norm without naming the file that norm came from would hand a model a
pre-fabricated, unsourced claim to cite -- the exact failure the grounding
rules exist to prevent. So every row is ``(axis, norm, origin)`` where
``origin`` is a repo-relative path that a reviewer can open, and a row whose
origin cannot be resolved from committed config is **not emitted at all**.
Thin cards are the correct output for a repo with thin config; an invented
norm is not.

Three properties this module must keep:

* **Deterministic.** No timestamps, no absolute paths, no dict-order dependence,
  explicit LF. Regenerating with no source change yields a byte-identical file,
  so a reviewer sees a card diff only when a source file actually moved.
* **Honest about presence, silent about prose.** Rows record that
  ``AGENTS.md`` exists; they never summarise what it says. Extracting a claim
  from prose would be fabrication with extra steps.
* **No network, no model calls.** Every value comes from a file on disk.

Card *lookup* (``resolve_repo_card``) is deliberately absent: resolution is
repo-scope concern, not grounding, and ``brief.py`` owns grounding and is
imported by the live waist lane. That belongs in a later pass.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import List, Optional, Sequence, Tuple

#: Where generated cards live, relative to the repository root.
CARDS_SUBDIR = Path(".harness") / "cards"

#: Authored rationale lives beside the cards but must never be mistaken for
#: one. The underscore prefix also sorts it ahead of ``<repo>.md`` files.
RATIONALE_SUBDIR = "_rationale"

#: A row of the card table. ``origin`` is always a repo-relative POSIX path.
Row = Tuple[str, str, str]

GENERATED_NOTICE = (
    "<!-- Generated by harness/repo_cards.py. Do not edit by hand. -->"
    "<!-- Every row cites the committed file it was parsed from; a row whose"
    " origin cannot be resolved is omitted rather than guessed. -->"
)

_AGENT_DOCS = ("AGENTS.md", "CLAUDE.md", ".cursorrules")

# Directories that are checkouts of *something else* rather than a repository
# with its own conventions. ``Harness-*`` are phase worktrees and ``wt-*`` are
# generic worktrees; neither has a philosophy distinct from its source repo.
_SKIP_PREFIXES = ("Harness-", "wt-")
_SKIP_NAMES = frozenset(("scratch",))
_SKIP_RE = re.compile(r"^test\d*$")

# Versioned planning checkouts, ``<repo>-v<NNN>-<label>`` (e.g.
# ``SCMessenger-v040-harness-plan``). These track a plan against a base repo
# they already carry the config of, so their cards come out row-identical to
# the base repo's. Two identical cards are a contract that will drift apart,
# so the base repo is carded and the planning checkout is not. The rule is a
# shape, not a hardcoded name, so the next planning checkout is skipped too.
_PLAN_CHECKOUT_RE = re.compile(r"-v\d+-")


# --------------------------------------------------------------------------
# tiny TOML reader
#
# The package floor is Python 3.9 (see ``requires-python`` and the CI matrix),
# so ``tomllib`` is unavailable. We only need section presence and scalar
# values, so a two-level scan is enough and keeps the module dependency-free.
# --------------------------------------------------------------------------
def _toml_sections(text: str) -> List[Tuple[str, List[str]]]:
    """Split a TOML document into ``(section, body_lines)`` pairs."""
    name = ""
    body: List[str] = []
    out: List[Tuple[str, List[str]]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            if name:
                out.append((name, body))
            name = stripped[1:-1].strip()
            body = []
        elif name:
            body.append(line)
    if name:
        out.append((name, body))
    return out


def _toml_value(text: str, section: str, key: str) -> Optional[str]:
    """Return a scalar from ``section`` as written, or ``None`` if absent."""
    for name, body in _toml_sections(text):
        if name != section:
            continue
        for line in body:
            if "=" not in line or line.lstrip().startswith("#"):
                continue
            found, _, raw = line.partition("=")
            if found.strip() == key:
                return raw.strip().strip('"').strip("'")
    return None


def _toml_has_section(text: str, section: str) -> bool:
    return any(name == section for name, _ in _toml_sections(text))


def _read(path: Path) -> Optional[str]:
    """Read a text file as UTF-8 with LF normalised, or ``None`` if unreadable."""
    try:
        return path.read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n")
    except OSError:
        return None


# --------------------------------------------------------------------------
# slot scanners -- each returns rows only when it can name an origin
# --------------------------------------------------------------------------
def _agent_context_rows(repo: Path) -> List[Row]:
    rows = []
    for name in _AGENT_DOCS:
        if (repo / name).is_file():
            rows.append(("Agent context", "`{}` is the agent-facing context".format(name), name))
    return rows


def _contributing_row(repo: Path) -> List[Row]:
    name = "CONTRIBUTING.md"
    return [("Contribution", "`{}` is the contribution guide".format(name), name)] \
        if (repo / name).is_file() else []


def _lint_rows(repo: Path) -> List[Row]:
    rows: List[Row] = []
    pyproject = _read(repo / "pyproject.toml")
    if pyproject and _toml_has_section(pyproject, "tool.ruff"):
        width = _toml_value(pyproject, "tool.ruff", "line-length")
        norm = "ruff is the linter"
        if width:
            norm += ", line length {}".format(width)
        rows.append(("Lint", norm, "pyproject.toml:[tool.ruff]"))
    # Harness declares its gates as argv data; cite the registry, not prose.
    gate_runner = repo / "harness" / "gate_runner.py"
    if gate_runner.is_file():
        text = _read(gate_runner) or ""
        if '"ruff"' in text and '"unittest"' in text:
            rows.append(
                ("Lint",
                 "quality gates are argv data in one registry, run shell-free",
                 "harness/gate_runner.py:GATES")
            )
    return rows


def _test_rows(repo: Path) -> List[Row]:
    rows: List[Row] = []
    gate_runner = repo / "harness" / "gate_runner.py"
    text = _read(gate_runner) if gate_runner.is_file() else None
    if text and '"unittest"' in text:
        rows.append(
            ("Tests", "hermetic suite, no network, warnings as errors",
             "harness/gate_runner.py:GATES")
        )
    cargo = _read(repo / "Cargo.toml")
    if cargo and _toml_has_section(cargo, "package"):
        rows.append(("Tests", "`cargo test` is the test command", "Cargo.toml:[package]"))
    package = _read(repo / "package.json")
    if package:
        try:
            scripts = json.loads(package).get("scripts") or {}
        except ValueError:
            scripts = {}
        if "test" in scripts:
            rows.append(("Tests", "`npm test` is the test command",
                         "package.json:scripts.test"))
    return rows


def _ci_rows(repo: Path) -> List[Row]:
    workflows = repo / ".github" / "workflows"
    if not workflows.is_dir():
        return []
    try:
        names = sorted(p.name for p in workflows.iterdir() if p.suffix in (".yml", ".yaml"))
    except OSError:
        return []
    return [
        ("CI", "workflow `{}` runs on push/pull request".format(name),
         ".github/workflows/{}".format(name))
        for name in names
    ]


def _build_rows(repo: Path) -> List[Row]:
    rows: List[Row] = []
    pyproject = _read(repo / "pyproject.toml")
    if pyproject and _toml_has_section(pyproject, "project"):
        name = _toml_value(pyproject, "project", "name")
        requires = _toml_value(pyproject, "project", "requires-python")
        norm = "Python package `{}`".format(name) if name else "Python package"
        if requires:
            norm += ", requires-python {}".format(requires)
        rows.append(("Build", norm, "pyproject.toml:[project]"))
    cargo = _read(repo / "Cargo.toml")
    if cargo and _toml_has_section(cargo, "package"):
        name = _toml_value(cargo, "package", "name")
        if name:
            rows.append(("Build", "Rust crate `{}`".format(name), "Cargo.toml:[package]"))
    package = _read(repo / "package.json")
    if package:
        try:
            name = json.loads(package).get("name")
        except ValueError:
            name = None
        rows.append(
            ("Build", "Node package `{}`".format(name) if name else "Node package",
             "package.json")
        )
    if (repo / "requirements.txt").is_file():
        rows.append(("Build", "Python dependencies pinned in `requirements.txt`",
                     "requirements.txt"))
    return rows


_SLOTS = (_agent_context_rows, _contributing_row, _lint_rows,
          _test_rows, _ci_rows, _build_rows)


def scan_repo(repo: Path) -> List[Row]:
    """Collect every card row for ``repo`` from its committed config.

    Slots run in a fixed order and each sorts its own rows, so the result is
    a pure function of what is on disk.
    """
    rows: List[Row] = []
    for slot in _SLOTS:
        rows.extend(slot(repo))
    return rows


def discover_repos(root: Path) -> List[Tuple[str, Path]]:
    """Return ``(name, path)`` for canonical sibling repos, sorted by name.

    A directory qualifies when it is a git checkout and is not a worktree of
    another repository. The test-repo and scratch directories are skipped.
    """
    try:
        entries = sorted(p for p in root.iterdir() if p.is_dir())
    except OSError:
        return []
    found = []
    for path in entries:
        name = path.name
        if name.startswith(_SKIP_PREFIXES) or name in _SKIP_NAMES or _SKIP_RE.match(name):
            continue
        if _PLAN_CHECKOUT_RE.search(name):
            continue
        if not (path / ".git").exists():
            continue
        found.append((name, path))
    return found


# --------------------------------------------------------------------------
# rendering
# --------------------------------------------------------------------------
def _cell(text: str) -> str:
    """Escape a value so it cannot break out of the table."""
    return text.replace("|", "\\|")


def render_card(repo_name: str, rows: Sequence[Row], rationale: Optional[str] = None) -> str:
    """Render one card. Pure: same inputs always give the same bytes."""
    lines = [GENERATED_NOTICE, "", "# {}".format(repo_name), ""]
    if rows:
        lines.append("| Axis | Norm | Origin |")
        lines.append("|---|---|---|")
        for axis, norm, origin in rows:
            lines.append("| {} | {} | `{}` |".format(_cell(axis), _cell(norm), _cell(origin)))
        lines.append("")
    else:
        lines.append("No conventions could be resolved from committed config.")
        lines.append("")
    if rationale:
        lines.extend(["## Rationale", "", rationale.strip(), ""])
    return "\n".join(lines)


def rationale_for(repo_name: str, rationale_dir: Path) -> Optional[str]:
    """Return authored rationale for a repo, or ``None`` when absent."""
    return _read(rationale_dir / "{}.md".format(repo_name))


def write_card(cards_dir: Path, repo_name: str, body: str) -> bool:
    """Write a card with LF endings. Returns True when the file changed."""
    cards_dir.mkdir(parents=True, exist_ok=True)
    path = cards_dir / "{}.md".format(repo_name)
    try:
        if path.is_file() and path.read_text(encoding="utf-8") == body:
            return False
    except OSError:
        pass
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(body)
    return True


def generate(root: Path, cards_dir: Path) -> Tuple[List[str], List[str]]:
    """Generate a card for every canonical repo under ``root``.

    Returns ``(changed, unchanged)`` repo names.
    """
    rationale_dir = cards_dir / RATIONALE_SUBDIR
    changed: List[str] = []
    unchanged: List[str] = []
    for name, path in discover_repos(root):
        body = render_card(name, scan_repo(path), rationale_for(name, rationale_dir))
        if write_card(cards_dir, name, body):
            changed.append(name)
        else:
            unchanged.append(name)
    return changed, unchanged


def default_root() -> Path:
    """The directory holding the sibling repositories (parent of this repo)."""
    return Path(__file__).resolve().parent.parent.parent


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Generate repo philosophy cards.")
    parser.add_argument("--root", type=Path, default=None,
                        help="directory containing the repositories to card")
    parser.add_argument("--cards", type=Path, default=None,
                        help="output directory for generated cards")
    parser.add_argument("--check", action="store_true",
                        help="report cards that would change; write nothing")
    args = parser.parse_args(argv)

    root = args.root or default_root()
    cards = args.cards or Path(__file__).resolve().parent.parent / CARDS_SUBDIR

    if args.check:
        rationale_dir = cards / RATIONALE_SUBDIR
        stale = []
        for name, path in discover_repos(root):
            body = render_card(name, scan_repo(path), rationale_for(name, rationale_dir))
            target = cards / "{}.md".format(name)
            if not target.is_file() or target.read_text(encoding="utf-8") != body:
                stale.append(name)
        for name in stale:
            print("stale: {}".format(name))
        print("{} card(s) would change".format(len(stale)) if stale else "cards up to date")
        return 1 if stale else 0

    changed, unchanged = generate(root, cards)
    for name in changed:
        print("wrote {}".format(name))
    for name in unchanged:
        print("unchanged {}".format(name))
    return 0


if __name__ == "__main__":  # pragma: no cover - operator entry point
    raise SystemExit(main())
