#!/usr/bin/env python3
"""Generate packs/fireworks.endpoints.json from the dated price snapshot.

EV-6 (canon): the snapshot is the source of truth for Fireworks rates, and
the committed pack is the only file code reads. This script is the one
reviewed owner of that derivation. It never touches the network.

  python audits/self/refresh_fireworks_pack.py          # write the pack
  python audits/self/refresh_fireworks_pack.py --check  # fail on drift

Rows enter the pack only when they are ``live-confirmed`` AND carry a
Standard input / cached / output triple. Unverified rows, Priority-only
figures, and reranker/embedding rates (a different unit) are left out.
A model is routable only when its model path is confirmed.
"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SNAPSHOT = HERE / "dogfood" / "fireworks-price-snapshot.md"
PACK = ROOT / "packs" / "fireworks.endpoints.json"
SNAPSHOT_REL = "audits/self/dogfood/fireworks-price-snapshot.md"

_CAPTURED = re.compile(r"\*\*Captured:\*\*\s*(\d{4}-\d{2}-\d{2})")
_TRIPLE = re.compile(r"^([0-9]+(?:\.[0-9]+)?) / ([0-9]+(?:\.[0-9]+)?) / ([0-9]+(?:\.[0-9]+)?)$")
_SLUG = re.compile(r"`([^`]+)`")


def _table_rows(text):
    """Cells of each row in the ``## Models`` table, header and rule skipped."""
    rows, in_models = [], False
    for line in text.splitlines():
        if line.startswith("## "):
            in_models = line.strip() == "## Models"
            continue
        if not in_models or not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 5 or cells[0] == "Model" or set(cells[0]) <= {"-"}:
            continue
        rows.append(cells)
    return rows


def build_pack(text):
    """The pack document for a snapshot text. Deterministic; no I/O."""
    captured = _CAPTURED.search(text)
    if not captured:
        raise ValueError("snapshot has no '**Captured:**' date")
    models = []
    for name, standard, status, path_cell, _priority in _table_rows(text):
        if status != "live-confirmed":
            continue
        triple = _TRIPLE.match(standard)
        if not triple:
            continue  # reranker/embedding: per-1M input only, a different unit
        slug_match = _SLUG.search(path_cell)
        slug = slug_match.group(1) if slug_match else None
        confirmed = path_cell.startswith("confirmed:") and slug is not None
        models.append({
            "name": name,
            "input": float(triple.group(1)),
            "cached_input": float(triple.group(2)),
            "output": float(triple.group(3)),
            "slug": slug,
            "path": f"accounts/fireworks/models/{slug}" if confirmed else None,
        })
    return {
        "_comment": ("Generated by audits/self/refresh_fireworks_pack.py from "
                     f"{SNAPSHOT_REL}. Do not hand-edit."),
        "source": SNAPSHOT_REL,
        "captured": captured.group(1),
        "unit": "usd_per_1m_tokens",
        "models": models,
    }


def render(pack):
    return json.dumps(pack, indent=2) + "\n"


def main(argv):
    text = SNAPSHOT.read_text(encoding="utf-8")
    rendered = render(build_pack(text))
    if "--check" in argv:
        committed = PACK.read_text(encoding="utf-8") if PACK.exists() else None
        if committed != rendered:
            sys.stderr.write("packs/fireworks.endpoints.json is out of date with "
                             "the snapshot; run refresh_fireworks_pack.py\n")
            return 1
        print("fireworks pack matches the snapshot")
        return 0
    with open(PACK, "w", encoding="utf-8", newline="\n") as f:
        f.write(rendered)
    print("wrote packs/fireworks.endpoints.json")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
